name: Lesson 5 SAST

on:
  push:
    branches:
      - lesson-5
jobs:
  security_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: execute the PyCharm security test
    steps:
      - uses: actions/checkout@v4
    
  build_and_test:
    needs: [security_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: PyCharm Python Security Scanner
        uses: tonybaloney/pycharm-security@1.25.1
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
